namespace AppInstallerCaller
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        Windows.Foundation.Collections.IObservableVector<Microsoft.Management.Deployment.AppCatalogReference> AppCatalogs{ get; };
        Windows.Foundation.Collections.IObservableVector<Microsoft.Management.Deployment.CatalogPackage> InstalledApps{ get; };
    }
}
